stages:
  - build
  - push
  # - deploy

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
  tags: [shell]

push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  tags: [shell]

